const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const logs=$("#logs");
let running=false,startedAt=0,ticker=null,wallet=null,hardware=null,selectedGpus=new Set(),blockHistory=[];
const time=()=>new Date().toLocaleTimeString();
const log=(text,type="info")=>{logs.textContent+="\n["+time()+"] "+type.toUpperCase()+"  "+text;logs.scrollTop=logs.scrollHeight};
const setMessage=(target,text,error=false)=>{target.textContent=text;target.classList.toggle("error",error)};
const formatKrk=atomic=>{const value=BigInt(atomic||0),whole=value/100000000n,fraction=(value%100000000n).toString().padStart(8,"0").replace(/0+$/,"");return whole.toLocaleString()+(fraction?"."+fraction:".00")};
const endpoint=()=>({nodeUrl:$("#nodeUrl").value,apiUrl:$("#apiUrl").value,authToken:$("#authToken").value});
const go=page=>{const button=$('.nav[data-page="'+page+'"]');$$(".nav").forEach(item=>item.classList.toggle("active",item===button));$$(".page").forEach(item=>item.hidden=item.dataset.page!==page)};
function syncHardwareAction(){const start=$("#startHardware"),stop=$("#stopHardware"),status=$("#hardwareMineStatus"),hasCompute=Number($("#cpuThreads").value)>0||selectedGpus.size>0;start.disabled=running||!wallet||!hasCompute;$("#start").disabled=running||!wallet||!hasCompute;stop.disabled=!running;if(running){start.textContent="Mining active";status.textContent="Mining with "+resourceLabel()+". Accepted blocks and KRK rewards appear on Overview.";status.classList.add("active")}else{start.textContent=wallet?"Start mining with selected hardware":"Set up wallet to mine";status.textContent=!wallet?"Unlock a mining wallet, then start with the selected CPU and GPU devices.":hasCompute?"Ready: "+resourceLabel()+". This will connect using your saved node settings.":"Select at least one CPU thread or one GPU before mining.";status.classList.remove("active")}}
function setRunning(value){running=value;$("#start").disabled=value||!wallet;$("#stop").disabled=!value;["#nodeUrl","#apiUrl","#authToken"].forEach(id=>$(id).disabled=value);$("#sideDot").classList.toggle("live",value);$("#sideText").textContent=value?"Mining active":"Miner stopped";syncHardwareAction()}
function updateElapsed(){if(!running)return;const seconds=Math.floor((Date.now()-startedAt)/1000),h=String(Math.floor(seconds/3600)).padStart(2,"0"),m=String(Math.floor(seconds%3600/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");$("#elapsed").textContent=h+":"+m+":"+s}
function resourceLabel(){const cpu=Number($("#cpuThreads").value),gpus=selectedGpus.size,intensity=Number($("#gpuIntensity").value);return(cpu?cpu+" CPU":"CPU off")+" · "+(gpus?`1 GPU @ ${intensity}%`:"GPU off")}
function syncCpu(value){const numeric=Number(value),bounded=Math.max(0,Math.min(Number($("#cpuThreads").max),Number.isFinite(numeric)?Math.trunc(numeric):0));$("#cpuThreads").value=bounded;$("#cpuThreadsHardware").value=bounded;$("#cpuValue").textContent=bounded;$("#cpuHardwareValue").textContent=bounded;localStorage.setItem("korek.cpuThreads",String(bounded));syncHardwareAction()}
function updateGpuCount(){$("#gpuCount").textContent=selectedGpus.size?"1 device":"CPU only";localStorage.setItem("korek.gpus",JSON.stringify([...selectedGpus]));syncHardwareAction()}
function syncGpuIntensity(value){const bounded=Math.max(10,Math.min(100,Math.trunc(Number(value)||100)));$("#gpuIntensity").value=bounded;$("#gpuIntensityValue").textContent=bounded;localStorage.setItem("korek.gpuIntensity",String(bounded));syncHardwareAction()}
function showWallet(summary){wallet=summary;$("#walletLocked").hidden=true;$("#walletOpen").hidden=false;$("#walletBanner").hidden=true;$("#walletAddress").textContent=summary.wormholeAddress;$("#transparentAddress").textContent=summary.transparentAddress;$("#walletShort").textContent="Mining account · "+summary.wormholeAddress.slice(0,12)+"…";$("#rewardAddress").textContent=summary.wormholeAddress;$("#rewardPageAddress").textContent=summary.wormholeAddress;$("#start").disabled=running;syncHardwareAction();refreshBalance().catch(()=>{})}
function lockWalletView(){wallet=null;$("#walletLocked").hidden=false;$("#walletOpen").hidden=true;$("#walletBanner").hidden=false;$("#rewardAddress").textContent="No wallet unlocked";$("#rewardPageAddress").textContent="Unlock a wallet";$("#balance").textContent=$("#rewardBalance").textContent="0.00";$("#start").disabled=true;syncHardwareAction()}
function showRecovery(phrase){const box=$("#recoveryWords");box.replaceChildren();phrase.split(" ").forEach((word,index)=>{const item=document.createElement("span");item.textContent=(index+1)+". "+word;box.append(item)});$("#recoveryBox").hidden=false;$("#phraseSaved").checked=false;$("#hideRecovery").disabled=true}
async function walletAction(work,working){try{setMessage($("#walletMessage"),working);const result=await work();if(result.canceled){setMessage($("#walletMessage"),"Canceled");return}showWallet(result);if(result.recoveryPhrase)showRecovery(result.recoveryPhrase);setMessage($("#walletMessage"),"Wallet encrypted and ready");log("Wallet unlocked · "+result.wormholeAddress)}catch(error){setMessage($("#walletMessage"),error.message,true);log(error.message,"error")}}
function rememberApiUrl(value){if(!value)return;$("#apiUrl").value=value;localStorage.setItem("korek.apiUrl",value)}
async function refreshBalance(){if(!wallet)throw new Error("Unlock a wallet first");const result=await window.korekMiner.wallet.balance(endpoint()),formatted=formatKrk(result.balance);rememberApiUrl(result.apiUrl);$("#balance").textContent=formatted;$("#rewardBalance").textContent=formatted;setMessage($("#sendMessage"),"Balance updated from "+result.apiUrl);return result}
function renderNode(result){$("#nodeVersion").textContent=result.version||"—";$("#nodeHeight").textContent=result.height??"—";$("#nodeWork").textContent=result.cumulativeWork||"0";$("#nodePeers").textContent=result.p2p?.connectedPeers??result.sync?.peers??0;$("#nodeSync").textContent=result.sync?.state||"Unknown";$("#nodeRole").textContent=result.validator?"Validator":"Node";$("#nodeStorage").textContent=result.persistent?"Enabled":"Not reported";$("#nodeP2p").textContent=result.p2p?.enabled?"Enabled":"Disabled";setMessage($("#nodePageMessage"),`Connected to ${result.name} · ${result.minerProtocol}`)}
async function checkNode(base=$("#nodeUrl").value){try{setMessage($("#controlMessage"),"Checking node…");const result=await window.korekMiner.status(base,$("#authToken").value);$("#nodeDot").classList.add("live");$("#nodeState").textContent=result.name+" · block "+result.height+" · "+result.sync.state;$("#height").textContent=result.height;setMessage($("#controlMessage"),"Connected · "+result.minerProtocol);renderNode(result);log("Connected to "+result.name+" at block "+result.height);if(wallet)await refreshBalance().catch(error=>log(error.message,"warning"));return result}catch(error){$("#nodeDot").classList.remove("live");$("#nodeState").textContent="Node unavailable";setMessage($("#controlMessage"),error.message,true);setMessage($("#nodePageMessage"),error.message,true);log(error.message,"error");throw error}}
function addBlock(block,reward){blockHistory.unshift({height:block.height,hash:block.hash,reward,time:new Date()});blockHistory=blockHistory.slice(0,25);const body=$("#blockRows");body.replaceChildren();for(const item of blockHistory){const row=document.createElement("tr"),cells=["#"+item.height,item.hash.slice(0,14)+"…",formatKrk(item.reward)+" KRK",resourceLabel(),item.time.toLocaleTimeString()];cells.forEach((value,index)=>{const cell=document.createElement("td");cell.textContent=value;if(index===1)cell.className="mono";row.append(cell)});body.append(row)}}
function renderHardware(){const cards=$("#hardwareCards");cards.replaceChildren();const data=[["PROCESSOR",hardware.cpu],["LOGICAL THREADS",hardware.threads],["SYSTEM MEMORY",(hardware.memoryTotal/1073741824).toFixed(1)+" GB"],["PLATFORM",hardware.platform.toUpperCase()]];data.forEach(([label,value])=>{const article=document.createElement("article");article.className="card";const small=document.createElement("small"),bold=document.createElement("b");small.textContent=label;bold.textContent=value;article.append(small,bold);cards.append(article)});const max=Math.max(1,hardware.threads),storedCpu=localStorage.getItem("korek.cpuThreads"),saved=storedCpu===null?Math.max(1,max-1):Math.max(0,Math.min(max,Number(storedCpu)||0));["#cpuThreads","#cpuThreadsHardware"].forEach(id=>$(id).max=max);$("#cpuMax").textContent=max;syncCpu(saved);const savedGpus=new Set(JSON.parse(localStorage.getItem("korek.gpus")||"[]")),list=$("#gpuList"),savedGpu=[...savedGpus].find(id=>hardware.gpu.some(device=>device.id===id&&device.usable!==false));selectedGpus=new Set(savedGpu?[savedGpu]:[]);list.replaceChildren();const cpuLabel=document.createElement("label"),cpuInput=document.createElement("input"),cpuText=document.createElement("span"),cpuName=document.createElement("b"),cpuStatus=document.createElement("small");cpuLabel.className="gpu-option";cpuInput.type="radio";cpuInput.name="korek-gpu";cpuInput.checked=!selectedGpus.size;cpuInput.onchange=()=>{if(cpuInput.checked){selectedGpus.clear();updateGpuCount()}};cpuName.textContent="GPU off";cpuStatus.textContent="Mine using CPU threads only";cpuText.append(cpuName,cpuStatus);cpuLabel.append(cpuInput,cpuText);list.append(cpuLabel);hardware.gpu.forEach((device,index)=>{const label=document.createElement("label");label.className="gpu-option";const input=document.createElement("input");input.type="radio";input.name="korek-gpu";input.disabled=device.usable===false;input.checked=selectedGpus.has(device.id);input.onchange=()=>{if(input.checked){selectedGpus=new Set([device.id]);updateGpuCount()}};const text=document.createElement("span"),name=document.createElement("b"),status=document.createElement("small");name.textContent=device.name;status.textContent=device.usable===false?"System fallback renderer — unavailable for mining":(index===0?"Primary · ":"")+"Experimental WebGPU SHA-256";text.append(name,status);label.append(input,text);list.append(label)});syncGpuIntensity(localStorage.getItem("korek.gpuIntensity")||100);updateGpuCount()}

$$(".nav").forEach(button=>button.onclick=()=>go(button.dataset.page));$$(".go-wallet").forEach(button=>button.onclick=()=>go("wallet"));$$(".go-hardware").forEach(button=>button.onclick=()=>go("hardware"));$$(".go-dashboard").forEach(button=>button.onclick=()=>go("dashboard"));
const savedNodeUrl=localStorage.getItem("korek.nodeUrl"),legacyMinerEndpoints=new Set(["http://127.0.0.1:9833","http://localhost:9833"]);if(savedNodeUrl&&!legacyMinerEndpoints.has(savedNodeUrl.replace(/\/$/,"")))$("#nodeUrl").value=savedNodeUrl;else localStorage.setItem("korek.nodeUrl",$("#nodeUrl").value);const savedApiUrl=localStorage.getItem("korek.apiUrl"),legacyLocalApis=new Set(["http://127.0.0.1:8365","http://localhost:8365"]);if(savedApiUrl&&!legacyLocalApis.has(savedApiUrl.replace(/\/$/,"")))$("#apiUrl").value=savedApiUrl;else localStorage.setItem("korek.apiUrl",$("#apiUrl").value);
$("#nodePageUrl").value=$("#nodeUrl").value;
$("#nodeUrl").onchange=()=>localStorage.setItem("korek.nodeUrl",$("#nodeUrl").value);$("#apiUrl").onchange=()=>localStorage.setItem("korek.apiUrl",$("#apiUrl").value);
$("#cpuThreads").oninput=event=>syncCpu(event.target.value);$("#cpuThreadsHardware").oninput=event=>syncCpu(event.target.value);
$("#gpuIntensity").oninput=event=>syncGpuIntensity(event.target.value);
$("#checkNode").onclick=()=>checkNode().catch(()=>{});
$("#checkNodePage").onclick=$("#refreshNode").onclick=()=>{const value=$("#nodePageUrl").value.trim();$("#nodeUrl").value=value;localStorage.setItem("korek.nodeUrl",value);checkNode(value).catch(()=>{})};
$("#createWallet").onclick=()=>walletAction(()=>window.korekMiner.wallet.create($("#createPassword").value),"Creating encrypted wallet…");
$("#openWallet").onclick=()=>walletAction(()=>window.korekMiner.wallet.open($("#openPassword").value),"Opening wallet…");
$("#restoreWallet").onclick=()=>walletAction(()=>window.korekMiner.wallet.restore({password:$("#restorePassword").value,mnemonic:$("#restorePhrase").value}),"Restoring wallet…");
$("#phraseSaved").onchange=event=>{$("#hideRecovery").disabled=!event.target.checked};
$("#hideRecovery").onclick=()=>{$("#recoveryWords").replaceChildren();$("#recoveryBox").hidden=true};
$("#lockWallet").onclick=async()=>{await window.korekMiner.wallet.lock();lockWalletView();setMessage($("#walletMessage"),"Wallet locked");log("Wallet locked")};
$("#refreshBalance").onclick=async()=>{try{await refreshBalance();setMessage($("#sendMessage"),"Balance updated")}catch(error){setMessage($("#sendMessage"),error.message,true)}};
$("#sendReward").onclick=async()=>{try{setMessage($("#sendMessage"),"Signing transaction…");const tx=await window.korekMiner.wallet.send({apiUrl:$("#apiUrl").value,nodeUrl:$("#nodeUrl").value,to:$("#sendTo").value.trim(),amount:$("#sendAmount").value.trim()});rememberApiUrl(tx.apiUrl);setMessage($("#sendMessage"),"Transaction submitted · "+tx.id);log("Reward transfer submitted · "+tx.id);await refreshBalance()}catch(error){setMessage($("#sendMessage"),error.message,true);log(error.message,"error")}};
async function startMining(){if(!wallet){go("wallet");setMessage($("#walletMessage"),"Create or open a wallet before mining",true);return}try{const input={...endpoint(),cpuThreads:Number($("#cpuThreads").value),gpuIds:[...selectedGpus],gpuIntensity:Number($("#gpuIntensity").value)},result=await window.korekMiner.start(input);startedAt=Date.now();setRunning(true);clearInterval(ticker);ticker=setInterval(updateElapsed,1000);setMessage($("#controlMessage"),"Mining to "+result.rewardAddress);$("#gpuRuntimeStatus").textContent=selectedGpus.size?"Starting selected WebGPU adapter…":"GPU disabled — CPU-only mining.";log("Mining started · "+resourceLabel()+" · rewards "+result.rewardAddress)}catch(error){setMessage($("#controlMessage"),error.message,true);$("#hardwareMineStatus").textContent=error.message;$("#hardwareMineStatus").classList.remove("active");log(error.message,"error")}}
async function stopMining(){await window.korekMiner.stop();setRunning(false);clearInterval(ticker);setMessage($("#controlMessage"),"Mining stopped safely");log("Mining stopped")}
$("#start").onclick=startMining;
$("#startHardware").onclick=startMining;
$("#stop").onclick=stopMining;
$("#stopHardware").onclick=stopMining;
$("#clearLogs").onclick=()=>{logs.textContent="KOREK Miner log cleared."};
$("#rescanHardware").onclick=async()=>{hardware=await window.korekMiner.hardware();renderHardware();log("Hardware profile refreshed")};

window.korekMiner.onUpdate(event=>{if(event.type==="block"){$("#blocks").textContent=event.stats.blocks;$("#rewards").textContent=formatKrk(event.stats.totalAtomic);$("#rate").textContent=event.stats.blocksPerMinute.toFixed(2);$("#height").textContent=event.block.height;if(event.balance!==null){$("#balance").textContent=formatKrk(event.balance);$("#rewardBalance").textContent=formatKrk(event.balance)}addBlock(event.block,event.minerPayout);log("Accepted verified proof for block #"+event.block.height+" · miner payout "+formatKrk(event.minerPayout)+" KRK (95% subsidy + fees)")}else if(event.type==="hashrate"){$("#cpuRate").textContent=Number(event.cpuHashrate||0).toLocaleString();$("#gpuRate").textContent=Number(event.gpuHashrate||0).toLocaleString()}else if(event.type==="gpu-status"){const text=event.state==="active"?`GPU active: ${event.adapter}${event.requested&&event.adapter!==event.requested?` (requested ${event.requested})`:""} · ${event.message}`:`GPU unavailable: ${event.message}`;setMessage($("#gpuRuntimeStatus"),text,event.state!=="active");log(text,event.state==="active"?"info":"warning")}else if(event.type==="rejected"){$("#rejected").textContent=event.rejected;log("Rejected share · "+event.message,"warning")}else if(event.type==="work"){setMessage($("#controlMessage"),"Hashing signed template for block #"+event.template.height);log("Received signed work template · difficulty "+event.template.difficulty)}else if(event.type==="status"){$("#height").textContent=event.status.height;$("#nodeState").textContent=event.status.name+" · block "+event.status.height+" · "+event.status.sync.state}else if(event.type==="error"){setMessage($("#controlMessage"),event.message,true);log(event.message,"error")}else if(event.type==="paused"){setMessage($("#controlMessage"),event.message,true);log(event.message,"warning")}else if(event.type==="stopped")setRunning(false)});
(async()=>{try{$("#appVersion").textContent="v"+await window.korekMiner.version();hardware=await window.korekMiner.hardware();renderHardware();const summary=await window.korekMiner.wallet.summary();summary?showWallet(summary):lockWalletView()}catch(error){log(error.message,"error")}})();
setInterval(async()=>{try{const value=await window.korekMiner.telemetry();$("#cpuLoad").textContent=value.cpuPercent.toFixed(1);const gpu=value.gpu[0];$("#gpuLoad").textContent=gpu?gpu.utilization:"—";$("#gpuTemp").textContent=gpu&&Number.isFinite(gpu.tempC)?gpu.tempC:"—";$("#gpuPower").textContent=gpu&&Number.isFinite(gpu.powerW)?gpu.powerW.toFixed(1):"—"}catch{}},2000);
