const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const logs=$("#logs");
let running=false,startedAt=0,ticker=null,wallet=null,hardware=null,selectedGpus=new Set(),blockHistory=[],lastGpuAdapter="";
const time=()=>new Date().toLocaleTimeString();
const log=(text,type="info")=>{logs.textContent+="\n["+time()+"] "+type.toUpperCase()+"  "+text;logs.scrollTop=logs.scrollHeight};
const setMessage=(target,text,error=false)=>{target.textContent=text;target.classList.toggle("error",error)};
const formatKrk=atomic=>{const value=BigInt(atomic||0),whole=value/100000000n,fraction=(value%100000000n).toString().padStart(8,"0").replace(/0+$/,"");return whole.toLocaleString()+(fraction?"."+fraction:".00")};
const endpoint=()=>({nodeUrl:$("#nodeUrl").value,apiUrl:$("#apiUrl").value,authToken:$("#authToken").value});
const go=page=>{const button=$('.nav[data-page="'+page+'"]');$$(".nav").forEach(item=>item.classList.toggle("active",item===button));$$(".page").forEach(item=>item.hidden=item.dataset.page!==page)};
function syncHardwareAction(){const start=$("#startHardware"),stop=$("#stopHardware"),status=$("#hardwareMineStatus"),hasCompute=Number($("#cpuThreads").value)>0||selectedGpus.size>0;start.disabled=running||!wallet||!hasCompute;$("#start").disabled=running||!wallet||!hasCompute;stop.disabled=!running;if(running){start.textContent="Mining active";status.textContent="Mining with "+resourceLabel()+". Accepted blocks and KRK rewards appear on Overview.";status.classList.add("active")}else{start.textContent=wallet?"Start mining with selected hardware":"Set up wallet to mine";status.textContent=!wallet?"Unlock a mining wallet, then start with the selected CPU and GPU devices.":hasCompute?"Ready: "+resourceLabel()+". This will connect using your saved node settings.":"Select at least one CPU thread or one GPU before mining.";status.classList.remove("active")}}
function setRunning(value){running=value;$("#start").disabled=value||!wallet;$("#stop").disabled=!value;["#nodeUrl","#apiUrl","#authToken"].forEach(id=>$(id).disabled=value);$("#sideDot").classList.toggle("live",value);$("#sideText").textContent=value?"Mining active":"Miner stopped";syncHardwareAction()}
function updateElapsed(){if(!running)return;const seconds=Math.floor((Date.now()-startedAt)/1000),h=String(Math.floor(seconds/3600)).padStart(2,"0"),m=String(Math.floor(seconds%3600/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");$("#elapsed").textContent=h+":"+m+":"+s}
function resourceLabel(){const cpu=Number($("#cpuThreads").value),gpus=selectedGpus.size,intensity=Number($("#gpuIntensity").value);return(cpu?cpu+" CPU":"CPU off")+" · "+(gpus?`1 GPU @ ${intensity}%`:"GPU off")}
function syncCpu(value){const numeric=Number(value),bounded=Math.max(0,Math.min(Number($("#cpuThreads").max),Number.isFinite(numeric)?Math.trunc(numeric):0));$("#cpuThreads").value=bounded;$("#cpuThreadsHardware").value=bounded;$("#cpuValue").textContent=bounded;$("#cpuHardwareValue").textContent=bounded;localStorage.setItem("korek.cpuThreads",String(bounded));syncHardwareAction()}
function updateGpuCount(){const selected=hardware?.gpu?.find(device=>selectedGpus.has(device.id));$("#gpuCount").textContent=selected?selected.name:"Off";localStorage.setItem("korek.gpus",JSON.stringify([...selectedGpus]));syncHardwareAction()}
function syncGpuIntensity(value){const bounded=Math.max(0,Math.min(100,Math.trunc(Number(value)||0))),gpu=hardware?.gpu?.[0];["#gpuIntensity","#gpuIntensityDashboard"].forEach(id=>$(id).value=bounded);$("#gpuIntensityValue").textContent=bounded;$("#gpuDashboardValue").textContent=bounded;selectedGpus=bounded>0&&gpu?.usable!==false?new Set([gpu.id]):new Set();$("#gpuRuntimeStatus").textContent=bounded>0?`GPU requested at ${bounded}% — runtime verification begins when mining starts.`:"GPU off.";localStorage.setItem("korek.gpuIntensity",String(bounded));updateGpuCount()}
function showWallet(summary){wallet=summary;$("#walletLocked").hidden=true;$("#walletOpen").hidden=false;$("#walletBanner").hidden=true;$("#walletAddress").textContent=summary.wormholeAddress;$("#transparentAddress").textContent=summary.transparentAddress;$("#walletShort").textContent="Mining account · "+summary.wormholeAddress.slice(0,12)+"…";$("#rewardAddress").textContent=summary.wormholeAddress;$("#rewardPageAddress").textContent=summary.wormholeAddress;$("#start").disabled=running;syncHardwareAction();refreshBalance().catch(()=>{})}
function lockWalletView(){wallet=null;$("#walletLocked").hidden=false;$("#walletOpen").hidden=true;$("#walletBanner").hidden=false;$("#rewardAddress").textContent="No wallet unlocked";$("#rewardPageAddress").textContent="Unlock a wallet";$("#balance").textContent=$("#rewardBalance").textContent="0.00";$("#start").disabled=true;syncHardwareAction()}
function showRecovery(phrase){const box=$("#recoveryWords");box.replaceChildren();phrase.split(" ").forEach((word,index)=>{const item=document.createElement("span");item.textContent=(index+1)+". "+word;box.append(item)});$("#recoveryBox").hidden=false;$("#phraseSaved").checked=false;$("#hideRecovery").disabled=true}
async function walletAction(work,working){try{setMessage($("#walletMessage"),working);const result=await work();if(result.canceled){setMessage($("#walletMessage"),"Canceled");return}showWallet(result);if(result.recoveryPhrase)showRecovery(result.recoveryPhrase);setMessage($("#walletMessage"),"Wallet encrypted and ready");log("Wallet unlocked · "+result.wormholeAddress)}catch(error){setMessage($("#walletMessage"),error.message,true);log(error.message,"error")}}
function rememberApiUrl(value){if(!value)return;$("#apiUrl").value=value;localStorage.setItem("korek.apiUrl",value)}
async function refreshBalance(){if(!wallet)throw new Error("Unlock a wallet first");const result=await window.korekMiner.wallet.balance(endpoint()),formatted=formatKrk(result.balance);rememberApiUrl(result.apiUrl);$("#balance").textContent=formatted;$("#rewardBalance").textContent=formatted;setMessage($("#sendMessage"),"Balance updated from "+result.apiUrl);return result}
function renderNodeBlocks(blocks=[]){const body=$("#nodeBlockRows");body.replaceChildren();if(!blocks.length){const row=document.createElement("tr");row.className="empty";row.innerHTML='<td colspan="5">No blocks reported</td>';body.append(row);return}for(const block of blocks){const row=document.createElement("tr"),miner=String(block.miner||"—"),cells=["#"+block.height,String(block.hash||"—").slice(0,14)+"…",miner.length>18?miner.slice(0,16)+"…":miner,formatKrk(block.reward||0)+" KRK",String(block.transactions?.length||0)];cells.forEach((value,index)=>{const cell=document.createElement("td");cell.textContent=value;if(index===1)cell.className="mono";row.append(cell)});body.append(row)}}
function renderNode(overview){const result=overview.status;$("#nodeVersion").textContent=result.version||"—";$("#nodeHeight").textContent=result.height??"—";$("#nodeLiveHeight").textContent="Block "+(result.height??"—");$("#nodeWork").textContent=result.cumulativeWork||"0";$("#nodePeers").textContent=result.p2p?.connectedPeers??result.sync?.peers??0;$("#nodeSync").textContent=result.sync?.state||"Unknown";$("#nodeRole").textContent=result.validator?"Validator":"Full node";$("#nodeStorage").textContent=result.persistent?"Enabled":"Not reported";$("#nodeP2p").textContent=result.p2p?.enabled?"Enabled":"Disabled";$("#nodeConnectionType").textContent="Remote";$("#nodeLocalProcess").textContent="Not running";$("#nodeConnectionMode").textContent="REMOTE NODE · CONNECTED";$("#nodeModeExplanation").textContent=`Connected to ${overview.connection.endpoint}. This app is using that node; it is not running the node process.`;setMessage($("#nodePageMessage"),`Remote connected · ${result.name} · ${result.minerProtocol}`);renderNodeBlocks(overview.blocks)}
async function checkNode(base=$("#nodeUrl").value,{quiet=false}={}){try{if(!quiet)setMessage($("#controlMessage"),"Connecting to remote node…");const overview=await window.korekMiner.node.overview(base),result=overview.status;$("#nodeDot").classList.add("live");$("#nodeState").textContent="Remote · "+result.name+" · block "+result.height;$("#height").textContent=result.height;if(!quiet)setMessage($("#controlMessage"),"Remote connected · "+result.minerProtocol);renderNode(overview);if(!quiet){log("Remote node connected · "+result.name+" at block "+result.height);if(wallet)await refreshBalance().catch(error=>log(error.message,"warning"))}return result}catch(error){$("#nodeDot").classList.remove("live");$("#nodeState").textContent="Remote node unavailable";$("#nodeConnectionMode").textContent="REMOTE NODE · DISCONNECTED";$("#nodeModeExplanation").textContent="This app is not running a local node and could not reach the configured remote endpoint.";setMessage($("#controlMessage"),error.message,true);setMessage($("#nodePageMessage"),error.message,true);if(!quiet)log(error.message,"error");throw error}}
function addBlock(block,reward){blockHistory.unshift({height:block.height,hash:block.hash,reward,time:new Date()});blockHistory=blockHistory.slice(0,25);const body=$("#blockRows");body.replaceChildren();for(const item of blockHistory){const row=document.createElement("tr"),cells=["#"+item.height,item.hash.slice(0,14)+"…",formatKrk(item.reward)+" KRK",resourceLabel(),item.time.toLocaleTimeString()];cells.forEach((value,index)=>{const cell=document.createElement("td");cell.textContent=value;if(index===1)cell.className="mono";row.append(cell)});body.append(row)}}
function renderHardware(){const cards=$("#hardwareCards");cards.replaceChildren();const data=[["CPU",hardware.cpu],["CPU THREADS",hardware.threads],["GPU",hardware.gpu[0]?.name||"No compatible physical GPU"],["PLATFORM",hardware.platform.toUpperCase()]];data.forEach(([label,value])=>{const article=document.createElement("article");article.className="card";const small=document.createElement("small"),bold=document.createElement("b");small.textContent=label;bold.textContent=value;article.append(small,bold);cards.append(article)});const max=Math.max(1,hardware.threads),storedCpu=localStorage.getItem("korek.cpuThreads"),saved=storedCpu===null?Math.max(1,max-1):Math.max(0,Math.min(max,Number(storedCpu)||0));["#cpuThreads","#cpuThreadsHardware"].forEach(id=>$(id).max=max);$("#cpuMax").textContent=max;$("#cpuMaxDashboard").textContent=max;syncCpu(saved);const gpu=hardware.gpu[0];$("#gpuDeviceDescription").textContent=gpu?`${gpu.name} · WebGPU compute with operating-system telemetry verification.`:"No compatible physical GPU detected. GPU mining is disabled.";["#gpuIntensity","#gpuIntensityDashboard"].forEach(id=>$(id).disabled=!gpu);syncGpuIntensity(gpu?localStorage.getItem("korek.gpuIntensity")||0:0)}

$$(".nav").forEach(button=>button.onclick=()=>{go(button.dataset.page);if(button.dataset.page==="node")checkNode($("#nodePageUrl").value,{quiet:true}).catch(()=>{})});$$(".go-wallet").forEach(button=>button.onclick=()=>go("wallet"));$$(".go-hardware").forEach(button=>button.onclick=()=>go("hardware"));$$(".go-dashboard").forEach(button=>button.onclick=()=>go("dashboard"));
const savedNodeUrl=localStorage.getItem("korek.nodeUrl"),legacyMinerEndpoints=new Set(["http://127.0.0.1:9833","http://localhost:9833"]);if(savedNodeUrl&&!legacyMinerEndpoints.has(savedNodeUrl.replace(/\/$/,"")))$("#nodeUrl").value=savedNodeUrl;else localStorage.setItem("korek.nodeUrl",$("#nodeUrl").value);const savedApiUrl=localStorage.getItem("korek.apiUrl"),legacyLocalApis=new Set(["http://127.0.0.1:8365","http://localhost:8365"]);if(savedApiUrl&&!legacyLocalApis.has(savedApiUrl.replace(/\/$/,"")))$("#apiUrl").value=savedApiUrl;else localStorage.setItem("korek.apiUrl",$("#apiUrl").value);
$("#nodePageUrl").value=$("#nodeUrl").value;
$("#nodeUrl").onchange=()=>localStorage.setItem("korek.nodeUrl",$("#nodeUrl").value);$("#apiUrl").onchange=()=>localStorage.setItem("korek.apiUrl",$("#apiUrl").value);
$("#cpuThreads").oninput=event=>syncCpu(event.target.value);$("#cpuThreadsHardware").oninput=event=>syncCpu(event.target.value);
$("#gpuIntensity").oninput=event=>syncGpuIntensity(event.target.value);
$("#gpuIntensityDashboard").oninput=event=>syncGpuIntensity(event.target.value);
$("#checkNode").onclick=()=>checkNode().catch(()=>{});
$("#checkNodePage").onclick=$("#refreshNode").onclick=()=>{const value=$("#nodePageUrl").value.trim();$("#nodeUrl").value=value;localStorage.setItem("korek.nodeUrl",value);checkNode(value).catch(()=>{})};
$("#createWallet").onclick=()=>walletAction(()=>window.korekMiner.wallet.create($("#createPassword").value),"Creating encrypted wallet…");
$("#openWallet").onclick=()=>walletAction(()=>window.korekMiner.wallet.open($("#openPassword").value),"Opening wallet…");
$("#restoreWallet").onclick=()=>walletAction(()=>window.korekMiner.wallet.restore({password:$("#restorePassword").value,mnemonic:$("#restorePhrase").value}),"Restoring wallet…");
$("#phraseSaved").onchange=event=>{$("#hideRecovery").disabled=!event.target.checked};
$("#hideRecovery").onclick=()=>{$("#recoveryWords").replaceChildren();$("#recoveryBox").hidden=true};
$("#lockWallet").onclick=async()=>{await window.korekMiner.wallet.lock();lockWalletView();setMessage($("#walletMessage"),"Wallet locked");log("Wallet locked")};
$("#refreshBalance").onclick=async()=>{try{await refreshBalance();setMessage($("#sendMessage"),"Balance updated")}catch(error){setMessage($("#sendMessage"),error.message,true)}};
$("#sendReward").onclick=async()=>{try{setMessage($("#sendMessage"),"Signing transaction…");const tx=await window.korekMiner.wallet.send({apiUrl:$("#apiUrl").value,nodeUrl:$("#nodeUrl").value,to:$("#sendTo").value.trim(),amount:$("#sendAmount").value.trim()});rememberApiUrl(tx.apiUrl);setMessage($("#sendMessage"),"Transaction submitted · "+tx.id);log("Reward transfer submitted · "+tx.id);await refreshBalance()}catch(error){setMessage($("#sendMessage"),error.message,true);log(error.message,"error")}};
async function startMining(){if(!wallet){go("wallet");setMessage($("#walletMessage"),"Create or open a wallet before mining",true);return}try{const input={...endpoint(),cpuThreads:Number($("#cpuThreads").value),gpuIds:[...selectedGpus],gpuIntensity:Number($("#gpuIntensity").value)},result=await window.korekMiner.start(input);startedAt=Date.now();setRunning(true);clearInterval(ticker);ticker=setInterval(updateElapsed,1000);setMessage($("#controlMessage"),"Mining to "+result.rewardAddress);$("#gpuRuntimeStatus").textContent=selectedGpus.size?"Starting selected WebGPU adapter…":"GPU disabled — CPU-only mining.";log("Mining started · "+resourceLabel()+" · rewards "+result.rewardAddress)}catch(error){setMessage($("#controlMessage"),error.message,true);$("#hardwareMineStatus").textContent=error.message;$("#hardwareMineStatus").classList.remove("active");log(error.message,"error")}}
async function stopMining(){await window.korekMiner.stop();setRunning(false);clearInterval(ticker);setMessage($("#controlMessage"),"Mining stopped safely");log("Mining stopped")}
$("#start").onclick=startMining;
$("#startHardware").onclick=startMining;
$("#stop").onclick=stopMining;
$("#stopHardware").onclick=stopMining;
$("#clearLogs").onclick=()=>{logs.textContent="KOREK Miner log cleared."};
$("#rescanHardware").onclick=async()=>{hardware=await window.korekMiner.hardware(true);renderHardware();log("Hardware profile refreshed")};

window.korekMiner.onUpdate(event=>{if(event.type==="block"){$("#blocks").textContent=event.stats.blocks;$("#rewards").textContent=formatKrk(event.stats.totalAtomic);$("#rate").textContent=event.stats.blocksPerMinute.toFixed(2);$("#height").textContent=event.block.height;if(event.balance!==null){$("#balance").textContent=formatKrk(event.balance);$("#rewardBalance").textContent=formatKrk(event.balance)}addBlock(event.block,event.minerPayout);log("Accepted verified proof for block #"+event.block.height+" · miner payout "+formatKrk(event.minerPayout)+" KRK (95% subsidy + fees)")}else if(event.type==="hashrate"){$("#cpuRate").textContent=Number(event.cpuHashrate||0).toLocaleString();$("#gpuRate").textContent=Number(event.gpuHashrate||0).toLocaleString()}else if(event.type==="gpu-status"){lastGpuAdapter=event.state==="active"?event.adapter:"";const text=event.state==="active"?`GPU verified: ${event.adapter}${event.requested&&event.adapter!==event.requested?` (requested ${event.requested})`:""} · ${event.message}`:`GPU unavailable: ${event.message}`;setMessage($("#gpuRuntimeStatus"),text,event.state!=="active");log(text,event.state==="active"?"info":"warning")}else if(event.type==="rejected"){$("#rejected").textContent=event.rejected;log("Rejected share · "+event.message,"warning")}else if(event.type==="work"){setMessage($("#controlMessage"),"Hashing signed template for block #"+event.template.height);log("Received signed work template · difficulty "+event.template.difficulty)}else if(event.type==="status"){$("#height").textContent=event.status.height;$("#nodeState").textContent="Remote · "+event.status.name+" · block "+event.status.height}else if(event.type==="error"){setMessage($("#controlMessage"),event.message,true);log(event.message,"error")}else if(event.type==="paused"){setMessage($("#controlMessage"),event.message,true);log(event.message,"warning")}else if(event.type==="stopped"){lastGpuAdapter="";setRunning(false)}});
(async()=>{try{$("#appVersion").textContent="v"+await window.korekMiner.version();hardware=await window.korekMiner.hardware();renderHardware();const summary=await window.korekMiner.wallet.summary();summary?showWallet(summary):lockWalletView()}catch(error){log(error.message,"error")}})();
setInterval(async()=>{try{const value=await window.korekMiner.telemetry();$("#cpuLoad").textContent=value.cpuPercent.toFixed(1);const gpu=value.gpu[0];$("#gpuLoad").textContent=gpu?gpu.utilization:"—";$("#gpuTemp").textContent=gpu&&Number.isFinite(gpu.tempC)?gpu.tempC:"—";$("#gpuPower").textContent=gpu&&Number.isFinite(gpu.powerW)?gpu.powerW.toFixed(1):"—";if(running&&selectedGpus.size&&gpu)setMessage($("#gpuRuntimeStatus"),`GPU verified: ${lastGpuAdapter||gpu.name} · OS load ${gpu.utilization}% · ${gpu.tempC}°C · ${Number.isFinite(gpu.powerW)?gpu.powerW.toFixed(1)+" W":"power unavailable"}`)}catch{}},2000);
setInterval(()=>{const page=$('.page[data-page="node"]');if(page&&!page.hidden)checkNode($("#nodePageUrl").value,{quiet:true}).catch(()=>{})},5000);
