const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const logs=$("#logs");
let running=false,startedAt=0,ticker=null,wallet=null,hardware=null,selectedGpus=new Set(),blockHistory=[];
const time=()=>new Date().toLocaleTimeString();
const log=(text,type="info")=>{logs.textContent+="\n["+time()+"] "+type.toUpperCase()+"  "+text;logs.scrollTop=logs.scrollHeight};
const setMessage=(target,text,error=false)=>{target.textContent=text;target.classList.toggle("error",error)};
const formatKrk=atomic=>{const value=BigInt(atomic||0),whole=value/100000000n,fraction=(value%100000000n).toString().padStart(8,"0").replace(/0+$/,"");return whole.toLocaleString()+(fraction?"."+fraction:".00")};
const endpoint=()=>({nodeUrl:$("#nodeUrl").value,apiUrl:$("#apiUrl").value,authToken:$("#authToken").value});
const go=page=>{const button=$('.nav[data-page="'+page+'"]');$$(".nav").forEach(item=>item.classList.toggle("active",item===button));$$(".page").forEach(item=>item.hidden=item.dataset.page!==page)};
function setRunning(value){running=value;$("#start").disabled=value||!wallet;$("#stop").disabled=!value;["#nodeUrl","#apiUrl","#authToken"].forEach(id=>$(id).disabled=value);$("#sideDot").classList.toggle("live",value);$("#sideText").textContent=value?"Mining active":"Miner stopped"}
function updateElapsed(){if(!running)return;const seconds=Math.floor((Date.now()-startedAt)/1000),h=String(Math.floor(seconds/3600)).padStart(2,"0"),m=String(Math.floor(seconds%3600/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");$("#elapsed").textContent=h+":"+m+":"+s}
function resourceLabel(){const cpu=Number($("#cpuThreads").value),gpus=selectedGpus.size;return cpu+" CPU · "+gpus+" GPU"}
function syncCpu(value){const bounded=Math.max(1,Math.min(Number($("#cpuThreads").max),Number(value)||1));$("#cpuThreads").value=bounded;$("#cpuThreadsHardware").value=bounded;$("#cpuValue").textContent=bounded;$("#cpuHardwareValue").textContent=bounded;localStorage.setItem("korek.cpuThreads",String(bounded))}
function updateGpuCount(){$("#gpuCount").textContent=selectedGpus.size+" device"+(selectedGpus.size===1?"":"s");localStorage.setItem("korek.gpus",JSON.stringify([...selectedGpus]))}
function showWallet(summary){wallet=summary;$("#walletLocked").hidden=true;$("#walletOpen").hidden=false;$("#walletBanner").hidden=true;$("#walletAddress").textContent=summary.wormholeAddress;$("#transparentAddress").textContent=summary.transparentAddress;$("#walletShort").textContent="Mining account · "+summary.wormholeAddress.slice(0,12)+"…";$("#rewardAddress").textContent=summary.wormholeAddress;$("#rewardPageAddress").textContent=summary.wormholeAddress;$("#start").disabled=running;refreshBalance().catch(()=>{})}
function lockWalletView(){wallet=null;$("#walletLocked").hidden=false;$("#walletOpen").hidden=true;$("#walletBanner").hidden=false;$("#rewardAddress").textContent="No wallet unlocked";$("#rewardPageAddress").textContent="Unlock a wallet";$("#balance").textContent=$("#rewardBalance").textContent="0.00";$("#start").disabled=true}
function showRecovery(phrase){const box=$("#recoveryWords");box.replaceChildren();phrase.split(" ").forEach((word,index)=>{const item=document.createElement("span");item.textContent=(index+1)+". "+word;box.append(item)});$("#recoveryBox").hidden=false;$("#phraseSaved").checked=false;$("#hideRecovery").disabled=true}
async function walletAction(work,working){try{setMessage($("#walletMessage"),working);const result=await work();if(result.canceled){setMessage($("#walletMessage"),"Canceled");return}showWallet(result);if(result.recoveryPhrase)showRecovery(result.recoveryPhrase);setMessage($("#walletMessage"),"Wallet encrypted and ready");log("Wallet unlocked · "+result.wormholeAddress)}catch(error){setMessage($("#walletMessage"),error.message,true);log(error.message,"error")}}
async function refreshBalance(){if(!wallet)throw new Error("Unlock a wallet first");const result=await window.korekMiner.wallet.balance($("#apiUrl").value),formatted=formatKrk(result.balance);$("#balance").textContent=formatted;$("#rewardBalance").textContent=formatted;return result}
async function checkNode(){try{setMessage($("#controlMessage"),"Checking node…");const result=await window.korekMiner.status($("#nodeUrl").value,$("#authToken").value);$("#nodeDot").classList.add("live");$("#nodeState").textContent=result.name+" · block "+result.height+" · "+result.sync.state;$("#height").textContent=result.height;setMessage($("#controlMessage"),"Connected · "+result.minerProtocol);log("Connected to "+result.name+" at block "+result.height);if(wallet)await refreshBalance().catch(()=>{});return result}catch(error){$("#nodeDot").classList.remove("live");$("#nodeState").textContent="Node unavailable";setMessage($("#controlMessage"),error.message,true);log(error.message,"error");throw error}}
function addBlock(block,reward){blockHistory.unshift({height:block.height,hash:block.hash,reward,time:new Date()});blockHistory=blockHistory.slice(0,25);const body=$("#blockRows");body.replaceChildren();for(const item of blockHistory){const row=document.createElement("tr"),cells=["#"+item.height,item.hash.slice(0,14)+"…",formatKrk(item.reward)+" KRK",resourceLabel(),item.time.toLocaleTimeString()];cells.forEach((value,index)=>{const cell=document.createElement("td");cell.textContent=value;if(index===1)cell.className="mono";row.append(cell)});body.append(row)}}
function renderHardware(){const cards=$("#hardwareCards");cards.replaceChildren();const data=[["PROCESSOR",hardware.cpu],["LOGICAL THREADS",hardware.threads],["SYSTEM MEMORY",(hardware.memoryTotal/1073741824).toFixed(1)+" GB"],["PLATFORM",hardware.platform.toUpperCase()]];data.forEach(([label,value])=>{const article=document.createElement("article");article.className="card";const small=document.createElement("small"),bold=document.createElement("b");small.textContent=label;bold.textContent=value;article.append(small,bold);cards.append(article)});const max=Math.max(1,hardware.threads),saved=Math.min(max,Number(localStorage.getItem("korek.cpuThreads"))||Math.max(1,max-1));["#cpuThreads","#cpuThreadsHardware"].forEach(id=>$(id).max=max);$("#cpuMax").textContent=max;syncCpu(saved);const savedGpus=new Set(JSON.parse(localStorage.getItem("korek.gpus")||"[]")),list=$("#gpuList");selectedGpus=new Set([...savedGpus].filter(id=>hardware.gpu.some(device=>device.id===id)));list.replaceChildren();if(!hardware.gpu.length){const empty=document.createElement("p");empty.className="muted";empty.textContent="No GPU was reported by the operating system.";list.append(empty)}hardware.gpu.forEach((device,index)=>{const label=document.createElement("label");label.className="gpu-option";const input=document.createElement("input");input.type="checkbox";input.checked=selectedGpus.has(device.id);input.onchange=()=>{input.checked?selectedGpus.add(device.id):selectedGpus.delete(device.id);updateGpuCount()};const text=document.createElement("span"),name=document.createElement("b"),status=document.createElement("small");name.textContent=device.name;status.textContent=(index===0?"Primary · ":"")+"Detected · GPU worker pending";text.append(name,status);label.append(input,text);list.append(label)});updateGpuCount()}

$$(".nav").forEach(button=>button.onclick=()=>go(button.dataset.page));$$(".go-wallet").forEach(button=>button.onclick=()=>go("wallet"));$$(".go-hardware").forEach(button=>button.onclick=()=>go("hardware"));$$(".go-dashboard").forEach(button=>button.onclick=()=>go("dashboard"));
$("#nodeUrl").value=localStorage.getItem("korek.nodeUrl")||$("#nodeUrl").value;$("#apiUrl").value=localStorage.getItem("korek.apiUrl")||$("#apiUrl").value;
$("#nodeUrl").onchange=()=>localStorage.setItem("korek.nodeUrl",$("#nodeUrl").value);$("#apiUrl").onchange=()=>localStorage.setItem("korek.apiUrl",$("#apiUrl").value);
$("#cpuThreads").oninput=event=>syncCpu(event.target.value);$("#cpuThreadsHardware").oninput=event=>syncCpu(event.target.value);
$("#checkNode").onclick=()=>checkNode().catch(()=>{});
$("#createWallet").onclick=()=>walletAction(()=>window.korekMiner.wallet.create($("#createPassword").value),"Creating encrypted wallet…");
$("#openWallet").onclick=()=>walletAction(()=>window.korekMiner.wallet.open($("#openPassword").value),"Opening wallet…");
$("#restoreWallet").onclick=()=>walletAction(()=>window.korekMiner.wallet.restore({password:$("#restorePassword").value,mnemonic:$("#restorePhrase").value}),"Restoring wallet…");
$("#phraseSaved").onchange=event=>{$("#hideRecovery").disabled=!event.target.checked};
$("#hideRecovery").onclick=()=>{$("#recoveryWords").replaceChildren();$("#recoveryBox").hidden=true};
$("#lockWallet").onclick=async()=>{await window.korekMiner.wallet.lock();lockWalletView();setMessage($("#walletMessage"),"Wallet locked");log("Wallet locked")};
$("#refreshBalance").onclick=async()=>{try{await refreshBalance();setMessage($("#sendMessage"),"Balance updated")}catch(error){setMessage($("#sendMessage"),error.message,true)}};
$("#sendReward").onclick=async()=>{try{setMessage($("#sendMessage"),"Signing transaction…");const tx=await window.korekMiner.wallet.send({apiUrl:$("#apiUrl").value,to:$("#sendTo").value.trim(),amount:$("#sendAmount").value.trim()});setMessage($("#sendMessage"),"Transaction submitted · "+tx.id);log("Reward transfer submitted · "+tx.id);await refreshBalance()}catch(error){setMessage($("#sendMessage"),error.message,true);log(error.message,"error")}};
$("#start").onclick=async()=>{try{const input={...endpoint(),cpuThreads:Number($("#cpuThreads").value),gpuIds:[...selectedGpus]},result=await window.korekMiner.start(input);startedAt=Date.now();setRunning(true);clearInterval(ticker);ticker=setInterval(updateElapsed,1000);setMessage($("#controlMessage"),"Mining to "+result.rewardAddress);log("Mining started · "+resourceLabel()+" · rewards "+result.rewardAddress)}catch(error){setMessage($("#controlMessage"),error.message,true);log(error.message,"error")}};
$("#stop").onclick=async()=>{await window.korekMiner.stop();setRunning(false);clearInterval(ticker);setMessage($("#controlMessage"),"Mining stopped safely");log("Mining stopped")};
$("#clearLogs").onclick=()=>{logs.textContent="KOREK Miner log cleared."};
$("#rescanHardware").onclick=async()=>{hardware=await window.korekMiner.hardware();renderHardware();log("Hardware profile refreshed")};

window.korekMiner.onUpdate(event=>{if(event.type==="block"){$("#blocks").textContent=event.stats.blocks;$("#rewards").textContent=formatKrk(event.stats.totalAtomic);$("#rate").textContent=event.stats.blocksPerMinute.toFixed(2);$("#height").textContent=event.block.height;if(event.balance!==null){$("#balance").textContent=formatKrk(event.balance);$("#rewardBalance").textContent=formatKrk(event.balance)}addBlock(event.block,event.block.reward);log("Accepted block #"+event.block.height+" · "+formatKrk(event.block.reward)+" KRK")}else if(event.type==="status"){$("#height").textContent=event.status.height;$("#nodeState").textContent=event.status.name+" · block "+event.status.height+" · "+event.status.sync.state}else if(event.type==="error"){setMessage($("#controlMessage"),event.message,true);log(event.message,"error")}else if(event.type==="paused"){setMessage($("#controlMessage"),event.message,true);log(event.message,"warning")}else if(event.type==="stopped")setRunning(false)});
(async()=>{try{$("#appVersion").textContent="v"+await window.korekMiner.version();hardware=await window.korekMiner.hardware();renderHardware();const summary=await window.korekMiner.wallet.summary();summary?showWallet(summary):lockWalletView()}catch(error){log(error.message,"error")}})();
